services:
  # --- SERVIÇO DO FRONTEND ---
  frontend:
    build:
      context: ./frontend 
      dockerfile: dockerfile
      args:
        VITE_PROXY_TARGET: http://backend:5000
    container_name: portfolio_frontend
    restart: always
    ports:
      - '8017:4173'
    environment:
      # Diz ao Vite (no preview) para onde apontar o proxy /api
      VITE_PROXY_TARGET: http://backend:5000
    depends_on:
      - backend

  # --- SERVIÇO DO BACKEND ---
  backend:
    build:
      context: ./backend 
      dockerfile: dockerfile
    container_name: portfolio_backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      MONGODB_URI: mongodb://mongo:27017/portfolio
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD} 
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      PORT: 5000
    volumes:
      # Monta a pasta de uploads para ser persistente
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo 

  # --- SERVIÇO DO MONGODB ---
  mongo:
    image: mongo:latest
    container_name: portfolio
    restart: always
    ports:
      - '27028:27017'
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data: 